spring:
  application:
    name: PRODUCTSERVICE
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/Cartly}
    username: ${SPRING_DATASOURCE_USERNAME:username}
    password: ${SPRING_DATASOURCE_PASSWORD:password}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
logging:
  level:
    org.springframework.security: TRACE
server:
  port: ${SERVER_PORT:8083}
minio:
  url: ${MINIO_URL:http://localhost:9000}
  public-url: ${MINIO_PUBLIC_URL:${MINIO_URL:http://localhost:9000}}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket: ${MINIO_BUCKET:cartlyminio}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
