spring:
  application:
    name: apigateway

  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
    gateway:
      server:
        webmvc:
          routes:
            - id: authservice-users
              uri: lb://AUTHSERVICE
              predicates:
                - Path=/api/users/**
            - id: productservice
              uri: lb://PRODUCTSERVICE
              predicates:
                - Path=/api/products/**
            - id: cartservice
              uri: lb://CARTSERVICE
              predicates:
                - Path=/api/shop/cart/**

server:
  port: ${SERVER_PORT:8081}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
